on:
  push:
    branches:
      - main
      - alpha
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        platform:
          - iOS
    steps:
      - uses: actions/checkout@v4
      - uses: mxcl/xcodebuild@v3.0.0
        with:
          platform: ${{ matrix.platform }}
          action: test
          scheme: Web3SwiftMpcProvider
          code-coverage: true
          upload-logs: always
